; This file is project specific and should be checked in to source control.

[mdk]
; This is a programmable block script project.
type=programmableblock

; Toggle trace (on|off) (verbose output)
trace=off

; What type of minification to use (none|trim|stripcomments|lite|full)
minify=full
interactive=DoNothing
; A list of files and folders to ignore when creating the script.
ignores=obj/**/*,MDK/**/*,**/*.debug.cs
