<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>JetOSExtensions.Client</AssemblyName>
    <RootNamespace>JetOSExtensions.Client</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Bin64 Condition="'$(Bin64)' == ''">G:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64</Bin64>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\JetOSExtensions.Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ProtoBuf.Net" HintPath="$(Bin64)\ProtoBuf.Net.dll" Private="False" />
    <Reference Include="Sandbox.Common" HintPath="$(Bin64)\Sandbox.Common.dll" Private="False" />
    <Reference Include="Sandbox.Game" HintPath="$(Bin64)\Sandbox.Game.dll" Private="False" />
    <Reference Include="Sandbox.Graphics" HintPath="$(Bin64)\Sandbox.Graphics.dll" Private="False" />
    <Reference Include="SharpDX" HintPath="$(Bin64)\SharpDX.dll" Private="False" />
    <Reference Include="SharpDX.Direct3D11" HintPath="$(Bin64)\SharpDX.Direct3D11.dll" Private="False" />
    <Reference Include="SharpDX.DXGI" HintPath="$(Bin64)\SharpDX.DXGI.dll" Private="False" />
    <Reference Include="SpaceEngineers.Game" HintPath="$(Bin64)\SpaceEngineers.Game.dll" Private="False" />
    <Reference Include="SpaceEngineers.ObjectBuilders" HintPath="$(Bin64)\SpaceEngineers.ObjectBuilders.dll" Private="False" />
    <Reference Include="VRage" HintPath="$(Bin64)\VRage.dll" Private="False" />
    <Reference Include="VRage.Audio" HintPath="$(Bin64)\VRage.Audio.dll" Private="False" />
    <Reference Include="VRage.Game" HintPath="$(Bin64)\VRage.Game.dll" Private="False" />
    <Reference Include="VRage.Input" HintPath="$(Bin64)\VRage.Input.dll" Private="False" />
    <Reference Include="VRage.Library" HintPath="$(Bin64)\VRage.Library.dll" Private="False" />
    <Reference Include="VRage.Math" HintPath="$(Bin64)\VRage.Math.dll" Private="False" />
    <Reference Include="VRage.Render" HintPath="$(Bin64)\VRage.Render.dll" Private="False" />
    <Reference Include="VRage.Render11" HintPath="$(Bin64)\VRage.Render11.dll" Private="False" />
    <Reference Include="VRage.Scripting" HintPath="$(Bin64)\VRage.Scripting.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Sandbox.Game" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="VRage.Render" IncludeCompilerGeneratedMembers="false" />
    <Publicize Include="VRage.Render11" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>

  <PropertyGroup>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
