<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Bin64 Condition="'$(Bin64)' == ''">G:\SteamLibrary\SteamApps\common\SpaceEngineers\Bin64</Bin64>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JetOSRadarFeed\JetOSRadarFeed.csproj" />
    <Reference Include="VRage.Game" HintPath="$(Bin64)\VRage.Game.dll" Private="True" />
  </ItemGroup>
</Project>
